version: '2'
services:
  build:
    image: node:lts-stretch-slim
    volumes:
      - .:/manage-fe
    command:
      - /bin/sh
      - -c
      - |
        cd /manage-fe
        npm install --registry=https://registry.npm.taobao.org
        npm run build --fix
